const soruBankasi = [
  { "harf_sayisi": 3, "soru": "Ağacın kolu", "cevap": "DAL" },
  { "harf_sayisi": 3, "soru": "Ağızdaki kemiksi organ", "cevap": "DİŞ" },
  { "harf_sayisi": 3, "soru": "Allah'a hizmet eden", "cevap": "KUL" },
  { "harf_sayisi": 3, "soru": "Ani ve şaşırtıcı olay", "cevap": "ŞOK" },
  { "harf_sayisi": 3, "soru": "Arının ürettiği tatlı besin", "cevap": "BAL" },
  { "harf_sayisi": 3, "soru": "Başın üstündeki kıllar", "cevap": "SAÇ" },
  { "harf_sayisi": 3, "soru": "Brütün karşıtı", "cevap": "NET" },
  { "harf_sayisi": 3, "soru": "Çeşit, cins", "cevap": "TÜR" },
  { "harf_sayisi": 3, "soru": "Damarlardaki kırmızı sıvı", "cevap": "KAN" },
  { "harf_sayisi": 3, "soru": "Demirin oksitlenmiş hali", "cevap": "PAS" },
  { "harf_sayisi": 3, "soru": "Donmuş su", "cevap": "BUZ" },
  { "harf_sayisi": 3, "soru": "Duvara monte edilen depolama düzlemi", "cevap": "RAF" },
  { "harf_sayisi": 3, "soru": "Duygu, sezgi", "cevap": "HİS" },
  { "harf_sayisi": 3, "soru": "Eski Türk hükümdarı", "cevap": "HAN" },
  { "harf_sayisi": 3, "soru": "Gezi, seyahat", "cevap": "TUR" },
  { "harf_sayisi": 3, "soru": "Görme organı", "cevap": "GÖZ" },
  { "harf_sayisi": 3, "soru": "Görüşü engelleyen duman", "cevap": "SİS" },
  { "harf_sayisi": 3, "soru": "Hayvan yiyeceği", "cevap": "YEM" },
  { "harf_sayisi": 3, "soru": "Islaklık, rutubet", "cevap": "NEM" },
  { "harf_sayisi": 3, "soru": "Işık geçirgenliği yüksek, ince dokuma", "cevap": "TÜL" },
  { "harf_sayisi": 3, "soru": "İletişim kablosu", "cevap": "TEL" },
  { "harf_sayisi": 3, "soru": "İnce, küçük zerre", "cevap": "TOZ" },
  { "harf_sayisi": 3, "soru": "Kapı veya bisikletteki sesli uyarıcı", "cevap": "ZİL" },
  { "harf_sayisi": 3, "soru": "Kıvamlı, sürülebilen madde", "cevap": "JEL" },
  { "harf_sayisi": 3, "soru": "Koyundan elde edilen iplik", "cevap": "YÜN" },
  { "harf_sayisi": 3, "soru": "Kuvvet, takat", "cevap": "GÜÇ" },
  { "harf_sayisi": 3, "soru": "Leke, pislik", "cevap": "KİR" },
  { "harf_sayisi": 3, "soru": "Omuza atılan dokuma", "cevap": "ŞAL" },
  { "harf_sayisi": 3, "soru": "Organik maddeler üzerindeki mikroskobik mantar kolonisi", "cevap": "KÜF" },
  { "harf_sayisi": 3, "soru": "Pencere malzemesi", "cevap": "CAM" },
  { "harf_sayisi": 3, "soru": "Saç kurutma aleti", "cevap": "FÖN" },
  { "harf_sayisi": 3, "soru": "Satrançta çapraz hareket eden taş", "cevap": "FİL" },
  { "harf_sayisi": 3, "soru": "Satrançta şahın tehdit altında kalarak oyunu kaybetmesi durumu", "cevap": "MAT" },
  { "harf_sayisi": 3, "soru": "Serinletici alet", "cevap": "FAN" },
  { "harf_sayisi": 3, "soru": "Sıcak içecek", "cevap": "ÇAY" },
  { "harf_sayisi": 3, "soru": "Temizlikte kullanılan dokuma", "cevap": "BEZ" },
  { "harf_sayisi": 3, "soru": "Tiyatroda canlandırılan kişilik", "cevap": "ROL" },
  { "harf_sayisi": 3, "soru": "Uzaktan kumanda güç kaynağı", "cevap": "PİL" },
  { "harf_sayisi": 3, "soru": "Vücudun bir uzvu", "cevap": "KOL" },
  { "harf_sayisi": 3, "soru": "Yakıt türü", "cevap": "GAZ" },
  { "harf_sayisi": 3, "soru": "Yanma reaksiyonunun katı artığı", "cevap": "KÜL" },
  { "harf_sayisi": 3, "soru": "Yanmakta olan odun parçası", "cevap": "KOR" },
  { "harf_sayisi": 3, "soru": "Yaşam, ruh", "cevap": "CAN" },
  { "harf_sayisi": 3, "soru": "Yön tayininde belirsizlik yaratan hava olayı", "cevap": "PUS" },
  { "harf_sayisi": 4, "soru": "Ahlak felsefesi", "cevap": "ETİK" },
  { "harf_sayisi": 4, "soru": "Ana gövdeden ayrılmış inanç grubu", "cevap": "SEKT" },
  { "harf_sayisi": 4, "soru": "Bazı İskandinav ülkelerinin para birimi", "cevap": "KRON" },
  { "harf_sayisi": 4, "soru": "Bir balık tutma aracı", "cevap": "OLTA" },
  { "harf_sayisi": 4, "soru": "Bir çıkar grubunun yasa dışı etkinlikleri", "cevap": "LOBİ" },
  { "harf_sayisi": 4, "soru": "Bir içecek", "cevap": "KOLA" },
  { "harf_sayisi": 4, "soru": "Bir iskambil kartı", "cevap": "VALE" },
  { "harf_sayisi": 4, "soru": "Bir iskambil rengi", "cevap": "MAÇA" },
  { "harf_sayisi": 4, "soru": "Bir odaya giriş yeri", "cevap": "KAPI" },
  { "harf_sayisi": 4, "soru": "Bir sanat veya düşünce akımı, okul", "cevap": "EKOL" },
  { "harf_sayisi": 4, "soru": "Bir tahıl", "cevap": "ARPA" },
  { "harf_sayisi": 4, "soru": "Bir takı", "cevap": "KÜPE" },
  { "harf_sayisi": 4, "soru": "Bir topluluğun ortaklaşa sahip olduğu değerlerin tümü", "cevap": "TÖRE" }, 
  { "harf_sayisi": 4, "soru": "Bir tür ışın", "cevap": "GAMA" },
  { "harf_sayisi": 4, "soru": "Bir yarışın bölümü, aşama", "cevap": "ETAP" },
  { "harf_sayisi": 4, "soru": "Birleştirici metal parça", "cevap": "VİDA" },
  { "harf_sayisi": 4, "soru": "Boks müsabakalarının yapıldığı kare alan", "cevap": "RİNG" },
  { "harf_sayisi": 4, "soru": "Cilde sürülen yumuşatıcı", "cevap": "KREM" },
  { "harf_sayisi": 4, "soru": "Cümlede iş, oluş bildiren kelime", "cevap": "FİİL" },
  { "harf_sayisi": 4, "soru": "Deniz ulaşım aracı", "cevap": "GEMİ" },
  { "harf_sayisi": 4, "soru": "Doğada konaklama etkinliği", "cevap": "KAMP" },
  { "harf_sayisi": 4, "soru": "Edebi ve sanatsal bir tarz", "cevap": "TEMA" },
  { "harf_sayisi": 4, "soru": "Eğitim görülen yer", "cevap": "OKUL" },
  { "harf_sayisi": 4, "soru": "Felsefede, öznenin dışında kalan her şey", "cevap": "OBJE" },
  { "harf_sayisi": 4, "soru": "Geometrik bir şekil", "cevap": "KARE" },
  { "harf_sayisi": 4, "soru": "Giysinin boyun kısmı", "cevap": "YAKA" },
  { "harf_sayisi": 4, "soru": "Halkın dinlendiği yeşil alan", "cevap": "PARK" },
  { "harf_sayisi": 4, "soru": "Hastalık tedavisinde kullanılan madde", "cevap": "İLAÇ" },
  { "harf_sayisi": 4, "soru": "Hükümdar, yönetici", "cevap": "KRAL" },
  { "harf_sayisi": 4, "soru": "İzin, müsaade", "cevap": "ONAY" },
  { "harf_sayisi": 4, "soru": "Kuşun evi", "cevap": "YUVA" },
  { "harf_sayisi": 4, "soru": "Küçük kemirgen", "cevap": "FARE" },
  { "harf_sayisi": 4, "soru": "Müzik eşliğinde ritmik hareket", "cevap": "DANS" },
  { "harf_sayisi": 4, "soru": "Müzik yazısı", "cevap": "NOTA" },
  { "harf_sayisi": 4, "soru": "Özel bir topluluğun kullandığı, genel dilden farklı deyişler", "cevap": "ARGO" },
  { "harf_sayisi": 4, "soru": "Popüler olan, geçerli olan", "cevap": "MODA" },
  { "harf_sayisi": 4, "soru": "Satrançtaki bir taş", "cevap": "KALE" },
  { "harf_sayisi": 4, "soru": "Savaş, cenk", "cevap": "HARP" },
  { "harf_sayisi": 4, "soru": "Şarkı söyleyen topluluk", "cevap": "KORO" },
  { "harf_sayisi": 4, "soru": "Türkiye'nin para birimi", "cevap": "LİRA" },
  { "harf_sayisi": 4, "soru": "Üzerinde yemek yenilen mobilya", "cevap": "MASA" },
  { "harf_sayisi": 4, "soru": "Yapıştırmaya yarayan şerit", "cevap": "BANT" },
  { "harf_sayisi": 4, "soru": "Yemek listesi", "cevap": "MENÜ" },
  { "harf_sayisi": 4, "soru": "Yiyecek saklanan yer", "cevap": "DEPO" },
  { "harf_sayisi": 5, "soru": "17. yüzyıl Avrupa'sında ortaya çıkan süslü sanat akımı", "cevap": "BAROK" },
  { "harf_sayisi": 5, "soru": "Acı bir baharat", "cevap": "BİBER" },
  { "harf_sayisi": 5, "soru": "Ağaç topluluğu", "cevap": "ORMAN" },
  { "harf_sayisi": 5, "soru": "Antik Yunan'da halkın toplandığı meydan, çarşı", "cevap": "AGORA" },
  { "harf_sayisi": 5, "soru": "Atletizmde bir atma sporu objesi", "cevap": "GÜLLE" },
  { "harf_sayisi": 5, "soru": "Bazı kart oyunlarında her kartın yerine geçebilen kart", "cevap": "JOKER" },
  { "harf_sayisi": 5, "soru": "Beyaz bir kuş", "cevap": "MARTI" },
  { "harf_sayisi": 5, "soru": "Bir avcı kuşu", "cevap": "ŞAHİN" },
  { "harf_sayisi": 5, "soru": "Bir işte yetkin kişi", "cevap": "UZMAN" },
  { "harf_sayisi": 5, "soru": "Bir Kümes hayvanı", "cevap": "HOROZ" },
  { "harf_sayisi": 5, "soru": "Bir müzik aleti", "cevap": "GİTAR" },
  { "harf_sayisi": 5, "soru": "Bir spor dalı", "cevap": "TENİS" },
  { "harf_sayisi": 5, "soru": "Bir şeyin kopyası, benzeri", "cevap": "MODEL" },
  { "harf_sayisi": 5, "soru": "Bir tiyatro eserinin bölümü", "cevap": "PERDE" },
  { "harf_sayisi": 5, "soru": "Bir tür narenciye", "cevap": "LİMON" },
  { "harf_sayisi": 5, "soru": "Büyük su kabı", "cevap": "BİDON" },
  { "harf_sayisi": 5, "soru": "Devlet memurlarının maaşlarının derece ve kademesini düzenleyen sistem", "cevap": "BAREM" },
  { "harf_sayisi": 5, "soru": "Dikenli bir hayvan", "cevap": "KİRPİ" },
  { "harf_sayisi": 5, "soru": "Doğruluğu sorgulanamayan, kanıtlanmamış öğreti", "cevap": "DOGMA" },
  { "harf_sayisi": 5, "soru": "Duvardaki resim", "cevap": "TABLO" },
  { "harf_sayisi": 5, "soru": "Eski tip sedir", "cevap": "DİVAN" },
  { "harf_sayisi": 5, "soru": "Fesleğenle yapılan İtalyan sosu", "cevap": "PESTO" },
  { "harf_sayisi": 5, "soru": "Fotoğraf veya pul koleksiyonu defteri", "cevap": "ALBÜM" },
  { "harf_sayisi": 5, "soru": "Genellikle bir direğe asılan, işaret olarak kullanılan kumaş parçası", "cevap": "FLAMA" },
  { "harf_sayisi": 5, "soru": "Harcama, masraf", "cevap": "GİDER" },
  { "harf_sayisi": 5, "soru": "Hastalara bakan meslek", "cevap": "HEKİM" },
  { "harf_sayisi": 5, "soru": "İnsan yüzü, çehre", "cevap": "SURET" },
  { "harf_sayisi": 5, "soru": "İstanbul'da bir deniz uzantısı", "cevap": "HALİÇ" },
  { "harf_sayisi": 5, "soru": "Kabuklu bir yemiş", "cevap": "CEVİZ" },
  { "harf_sayisi": 5, "soru": "Kanatlı, masalsı varlık", "cevap": "MELEK" },
  { "harf_sayisi": 5, "soru": "Karadeniz'e özgü bir balık", "cevap": "HAMSİ" },
  { "harf_sayisi": 5, "soru": "Maç sonucu", "cevap": "SONUÇ" },
  { "harf_sayisi": 5, "soru": "Madde, nesne", "cevap": "CİSİM" },
  { "harf_sayisi": 5, "soru": "Meyve ve sebze satılan yer", "cevap": "MANAV" },
  { "harf_sayisi": 5, "soru": "Mizahi ve eleştirel yazı türü", "cevap": "HİCİV" },
  { "harf_sayisi": 5, "soru": "Naz, işve", "cevap": "CİLVE" },
  { "harf_sayisi": 5, "soru": "Okunan, yazılı eser", "cevap": "KİTAP" },
  { "harf_sayisi": 5, "soru": "Omuza asılan eski tip çanta", "cevap": "HEYBE" },
  { "harf_sayisi": 5, "soru": "Organik kimyada bir bileşik türü", "cevap": "KETON" },
  { "harf_sayisi": 5, "soru": "Oturma odası", "cevap": "SALON" },
  { "harf_sayisi": 5, "soru": "Romanya'nın güneyindeki tarihi bölge", "cevap": "EFLAK" },
  { "harf_sayisi": 5, "soru": "Sadık ev hayvanı", "cevap": "KÖPEK" },
  { "harf_sayisi": 5, "soru": "Sert bir metal", "cevap": "ÇELİK" },
  { "harf_sayisi": 5, "soru": "Ses yayını yapan cihaz", "cevap": "RADYO" },
  { "harf_sayisi": 5, "soru": "Sıkıntı, dert", "cevap": "GAİLE" },
  { "harf_sayisi": 5, "soru": "Son, bitiş, nihayet", "cevap": "HİTAM" },
  { "harf_sayisi": 5, "soru": "Söylenenin tersini kastederek yapılan ince alay", "cevap": "İRONİ" },
  { "harf_sayisi": 5, "soru": "Suda yaşayan büyük memeli", "cevap": "YUNUS" },
  { "harf_sayisi": 5, "soru": "Tasa, kaygı, üzüntü", "cevap": "EFKAR" },
  { "harf_sayisi": 5, "soru": "Tatlı, beyaz kristal", "cevap": "ŞEKER" },
  { "harf_sayisi": 5, "soru": "Temizlik veya boya yapma aleti", "cevap": "FIRÇA" },
  { "harf_sayisi": 5, "soru": "Tren vagonu", "cevap": "VAGON" },
  { "harf_sayisi": 5, "soru": "Uçak kullanan kişi", "cevap": "PİLOT" },
  { "harf_sayisi": 5, "soru": "Yarışmacı, hasım", "cevap": "RAKİP" },
  { "harf_sayisi": 5, "soru": "Yasa, kural, ilke", "cevap": "KANUN" },
  { "harf_sayisi": 5, "soru": "Yaşadığımız gezegen", "cevap": "DÜNYA" },
  { "harf_sayisi": 5, "soru": "Yaz meyvesi, sarı ve tatlı", "cevap": "KAVUN" },
  { "harf_sayisi": 5, "soru": "Yazı yazma aracı", "cevap": "KALEM" },
  { "harf_sayisi": 5, "soru": "Yeni dikilmiş ağaç", "cevap": "FİDAN" },
  { "harf_sayisi": 5, "soru": "Yere serilen dokuma", "cevap": "KİLİM" },
  { "harf_sayisi": 5, "soru": "Yerin altından geçen yol", "cevap": "TÜNEL" },
  { "harf_sayisi": 5, "soru": "Yeşil bir sebze", "cevap": "BAMYA" },
  { "harf_sayisi": 6, "soru": "Ağaç veya metal üzerine oyularak yapılan resim", "cevap": "GRAVÜR" },
  { "harf_sayisi": 6, "soru": "Alışveriş yapılan yer", "cevap": "MARKET" },
  { "harf_sayisi": 6, "soru": "Ameliyat yapan kişi", "cevap": "CERRAH" }, 
  { "harf_sayisi": 6, "soru": "Arazi parçası", "cevap": "PARSEL" },
  { "harf_sayisi": 6, "soru": "Aynı kimyasal formüle sahip farklı yapıda molekül", "cevap": "İZOMER" },
  { "harf_sayisi": 6, "soru": "Ayrılık acısı, keder", "cevap": "HİCRAN" },
  { "harf_sayisi": 6, "soru": "Belirli bir coğrafyadaki canlı topluluğu", "cevap": "BİYOM" },
  { "harf_sayisi": 6, "soru": "Belli bir meslek veya gruba özgü özel dil", "cevap": "JARGON" },
  { "harf_sayisi": 6, "soru": "Benekli bir kedi türü", "cevap": "LEOPAR" },
  { "harf_sayisi": 6, "soru": "Beyaz etli bir balık", "cevap": "LEVREK" },
  { "harf_sayisi": 6, "soru": "Bilimsel yazı türü", "cevap": "MAKALE" },
  { "harf_sayisi": 6, "soru": "Binanın dışa çıkıntılı bölümü", "cevap": "BALKON" },
  { "harf_sayisi": 6, "soru": "Bir düşüncenin veya ürünün eskimiş, geçerliliğini yitirmiş hali", "cevap": "DEMODE" },
  { "harf_sayisi": 6, "soru": "Bir görevden kendi isteğiyle ayrılma", "cevap": "İSTİFA" },
  { "harf_sayisi": 6, "soru": "Bir işin ön çalışması", "cevap": "TASLAK" },
  { "harf_sayisi": 6, "soru": "Bir işin yapılması için gereken süre", "cevap": "MÜDDET" },
  { "harf_sayisi": 6, "soru": "Bir kurumu veya düşünceyi simgeleyen özel işaret", "cevap": "AMBLEM" },
  { "harf_sayisi": 6, "soru": "Bir mesleğin yetki belgesi", "cevap": "RUHSAT" },
  { "harf_sayisi": 6, "soru": "Bir olayın veya durumun alaycı bir şekilde eleştirilmesi", "cevap": "PARODİ" },
  { "harf_sayisi": 6, "soru": "Bir spor takımının lideri", "cevap": "KAPTAN" },
  { "harf_sayisi": 6, "soru": "Bir spor türü", "cevap": "BASKET" },
  { "harf_sayisi": 6, "soru": "Bir şeyin eksikliği", "cevap": "NOKSAN" },
  { "harf_sayisi": 6, "soru": "Bir şeyin merkezi", "cevap": "MERKEZ" },
  { "harf_sayisi": 6, "soru": "Bir şeyin sonucu", "cevap": "NETİCE" },
  { "harf_sayisi": 6, "soru": "Bir tür başlık", "cevap": "KASKET" },
  { "harf_sayisi": 6, "soru": "Birine verilen armağan", "cevap": "HEDİYE" },
  { "harf_sayisi": 6, "soru": "Çaydanlık", "cevap": "DEMLİK" },
  { "harf_sayisi": 6, "soru": "Çok bilen, alim kişi", "cevap": "BİLGİN" },
  { "harf_sayisi": 6, "soru": "Dilbilgisinde tamlama", "cevap": "İZAFET" },
  { "harf_sayisi": 6, "soru": "Dokunmatik ekranlı cihaz", "cevap": "TABLET" },
  { "harf_sayisi": 6, "soru": "Eşya taşımak için kutu", "cevap": "SANDIK" },
  { "harf_sayisi": 6, "soru": "Geçmişte yaşanmış olayları anlatan yazı", "cevap": "HİKAYE" },
  { "harf_sayisi": 6, "soru": "Gemilerin yanaştığı yer", "cevap": "İSKELE" },
  { "harf_sayisi": 6, "soru": "Giysinin omuzdan bele inen kesik parçası", "cevap": "JAPONE" },
  { "harf_sayisi": 6, "soru": "Günlük notların tutulduğu defter", "cevap": "AJANDA" },
  { "harf_sayisi": 6, "soru": "Güzel koku", "cevap": "PARFÜM" },
  { "harf_sayisi": 6, "soru": "Halk arasında anlatılan olağanüstü hikaye", "cevap": "EFSANE" },
  { "harf_sayisi": 6, "soru": "Hukuk, hak", "cevap": "ADALET" },
  { "harf_sayisi": 6, "soru": "İlaç kullanım tarifi", "cevap": "REÇETE" },
  { "harf_sayisi": 6, "soru": "Kan bağı olan kimse", "cevap": "AKRABA" },
  { "harf_sayisi": 6, "soru": "Kendini başkasının yerine koyma yeteneği", "cevap": "EMPATİ" },
  { "harf_sayisi": 6, "soru": "Klasik Türk müziğinde bir makam", "cevap": "HÜZZAM" },
  { "harf_sayisi": 6, "soru": "Otobüslerin kalktığı yer", "cevap": "OTOGAR" },
  { "harf_sayisi": 6, "soru": "Oturmak için kullanılan, genellikle tek kişilik mobilya", "cevap": "KOLTUK" },
  { "harf_sayisi": 6, "soru": "Oturmaya yarayan mobilya", "cevap": "KANEPE" },
  { "harf_sayisi": 6, "soru": "Özlem", "cevap": "HASRET" },
  { "harf_sayisi": 6, "soru": "Para cüzdanı", "cevap": "CÜZDAN" },
  { "harf_sayisi": 6, "soru": "Parçaları birleştirme", "cevap": "MONTAJ" },
  { "harf_sayisi": 6, "soru": "Saçma, akla aykırı", "cevap": "ABSÜRT" },
  { "harf_sayisi": 6, "soru": "Saklı hazine", "cevap": "DEFİNE" },
  { "harf_sayisi": 6, "soru": "Sanat eserlerinin sergilendiği yer", "cevap": "GALERİ" },
  { "harf_sayisi": 6, "soru": "Sıvıyı süzen alet", "cevap": "FİLTRE" },
  { "harf_sayisi": 6, "soru": "Suda veya havada oluşan tehlikeli dönüntü", "cevap": "GİRDAP" },
  { "harf_sayisi": 6, "soru": "Topluluk, cemiyet", "cevap": "DERNEK" },
  { "harf_sayisi": 6, "soru": "Toplumsal düzeni sağlayan kurallar", "cevap": "ADALET" },
  { "harf_sayisi": 6, "soru": "Trafik işareti levhası", "cevap": "TABELA" },
  { "harf_sayisi": 6, "soru": "Venedik'e özgü kayık", "cevap": "GONDOL" },
  { "harf_sayisi": 6, "soru": "Vücut yapısı", "cevap": "BÜNYE" },
  { "harf_sayisi": 6, "soru": "Yanardağ", "cevap": "VOLKAN" },
  { "harf_sayisi": 6, "soru": "Yön bulmaya yarayan alet", "cevap": "PUSULA" },
  { "harf_sayisi": 6, "soru": "Yumuşak, parlak bir kumaş türü", "cevap": "KADİFE" },
  { "harf_sayisi": 6, "soru": "Yurt dışı, vatan hasreti", "cevap": "GURBET" },
  { "harf_sayisi": 6, "soru": "Yüksek bir yerden hızla düşen su kütlesi", "cevap": "ŞELALE" }, 
  { "harf_sayisi": 7, "soru": "Adam öldürme suçu", "cevap": "CİNAYET" },
  { "harf_sayisi": 7, "soru": "Başarı gösterenlere verilen metal nişan", "cevap": "MADALYA" },
  { "harf_sayisi": 7, "soru": "Beklenmedik ve büyük başarısızlık", "cevap": "FİYASKO" },
  { "harf_sayisi": 7, "soru": "Binanın dışarıya bakan, camlı bölümü", "cevap": "PENCERE" },
  { "harf_sayisi": 7, "soru": "Bir devletin temel yasası", "cevap": "ANAYASA" },
  { "harf_sayisi": 7, "soru": "Bir filmde veya oyunda küçük rol alan kimse", "cevap": "FİGÜRAN" },
  { "harf_sayisi": 7, "soru": "Bir hükümetin veya partinin temel görüş ve ilkeler bütünü", "cevap": "DOKTRİN" },
  { "harf_sayisi": 7, "soru": "Bir işin yapılması için gerekli olan araç ve gereçlerin tümü", "cevap": "MALZEME" },
  { "harf_sayisi": 7, "soru": "Bir konuyu aydınlatmak için yapılan konuşma", "cevap": "SÖYLEŞİ" },
  { "harf_sayisi": 7, "soru": "Bir sıvının içinde katı bir maddenin çözünmesiyle oluşan karışım", "cevap": "ÇÖZELTİ" },
  { "harf_sayisi": 7, "soru": "Bir şeyi güvence altına alma", "cevap": "SİGORTA" },
  { "harf_sayisi": 7, "soru": "Bir şeyin nasıl yapılacağını gösteren kurallar bütünü", "cevap": "YÖNERGE" },
  { "harf_sayisi": 7, "soru": "Bir şirketin belirli bir dönemdeki alacak ve borç durumu", "cevap": "BİLANÇO" },
  { "harf_sayisi": 7, "soru": "Bir ülkenin yönetim merkezi olan şehir", "cevap": "BAŞKENT" }, 
  { "harf_sayisi": 7, "soru": "Bir yapının veya eserin kopyası", "cevap": "REPLİKA" },
  { "harf_sayisi": 7, "soru": "Bir yer ayırtma işlemi", "cevap": "REZERVE" },
  { "harf_sayisi": 7, "soru": "Bir yerden bir yere mal taşıma", "cevap": "NAKLİYE" },
  { "harf_sayisi": 7, "soru": "Birine bir işi yapması için yetki verme", "cevap": "VEKALET" },
  { "harf_sayisi": 7, "soru": "Büyük yıkım, afet", "cevap": "FELAKET" },
  { "harf_sayisi": 7, "soru": "Cıva ile bir veya birkaç metalin oluşturduğu alaşım", "cevap": "AMALGAM" },
  { "harf_sayisi": 7, "soru": "Devleti yöneten organ", "cevap": "YÖNETİM" },
  { "harf_sayisi": 7, "soru": "Düşünür", "cevap": "FİLOZOF" },
  { "harf_sayisi": 7, "soru": "Engel, set", "cevap": "BARİYER" },
  { "harf_sayisi": 7, "soru": "Esnek, gerilebilir", "cevap": "ELASTİK" },
  { "harf_sayisi": 7, "soru": "Güvence", "cevap": "TEMİNAT" },
  { "harf_sayisi": 7, "soru": "Güvenlik teşkilatı", "cevap": "EMNİYET" },
  { "harf_sayisi": 7, "soru": "Hayvanları inceleyen bilim dalı", "cevap": "ZOOLOJİ" }, 
  { "harf_sayisi": 7, "soru": "İki ayrı telefonun aynı anda konuşmasını sağlayan sistem", "cevap": "DİYAFON" },
  { "harf_sayisi": 7, "soru": "İltihap, irin", "cevap": "CERAHAT" },
  { "harf_sayisi": 7, "soru": "Kapı ve kilitleri açan alet", "cevap": "ANAHTAR" },
  { "harf_sayisi": 7, "soru": "Mikroskobik canlı", "cevap": "BAKTERİ" },
  { "harf_sayisi": 7, "soru": "Olağanüstü veya hayranlık uyandıran olay veya kişi", "cevap": "FENOMEN" },
  { "harf_sayisi": 7, "soru": "Para alan görevli", "cevap": "KASİYER" },
  { "harf_sayisi": 7, "soru": "Patlayıcı madde", "cevap": "DİNAMİT" },
  { "harf_sayisi": 7, "soru": "Resim çerçevesi", "cevap": "ÇERÇEVE" },
  { "harf_sayisi": 7, "soru": "Sahne oyunu", "cevap": "TİYATRO" },
  { "harf_sayisi": 7, "soru": "Sahne veya ekran performansı", "cevap": "GÖSTERİ" },
  { "harf_sayisi": 7, "soru": "Sınav", "cevap": "İMTİHAN" },
  { "harf_sayisi": 7, "soru": "Sıra dışı, aşırı, uç", "cevap": "EKSTREM" },
  { "harf_sayisi": 7, "soru": "Soluduğumuz gaz", "cevap": "OKSİJEN" },
  { "harf_sayisi": 7, "soru": "Tıp alanında ameliyat ile ilgili", "cevap": "CERRAHİ" },
  { "harf_sayisi": 7, "soru": "Uzak mesafe iletişim aracı", "cevap": "TELEFON" },
  { "harf_sayisi": 7, "soru": "Üretim, dağıtım ve tüketim bilimi", "cevap": "İKTİSAT" }, // Düzeltildi: EKONOMİ 7 harfliydi
  { "harf_sayisi": 7, "soru": "Vücudumuz için gerekli organik bileşik", "cevap": "VİTAMİN" },
  { "harf_sayisi": 7, "soru": "Vücudun kemik çatısı", "cevap": "İSKELET" },
  { "harf_sayisi": 7, "soru": "Yağmurdan koruyan alet", "cevap": "ŞEMSİYE" },
  { "harf_sayisi": 7, "soru": "Yaşlı kimse", "cevap": "İHTİYAR" },
  { "harf_sayisi": 7, "soru": "Yer bilimi", "cevap": "JEOLOJİ" },
  { "harf_sayisi": 7, "soru": "Yıldızlar ve gezegenler sistemi", "cevap": "GALAKSİ" }, 
  { "harf_sayisi": 7, "soru": "Yol gösteren kitapçık", "cevap": "KILAVUZ" }, 
  { "harf_sayisi": 7, "soru": "Zıplayan bir böcek", "cevap": "ÇEKİRGE" },
  { "harf_sayisi": 8, "soru": "Bilgilendirici film", "cevap": "BELGESEL" },
  { "harf_sayisi": 8, "soru": "Bilgileri görselleştiren şema", "cevap": "DİYAGRAM" },
  { "harf_sayisi": 8, "soru": "Bina tasarlama sanatı", "cevap": "MİMARLIK" },
  { "harf_sayisi": 8, "soru": "Bir dilden başka bir dile çeviri yapan kişi", "cevap": "TERCÜMAN" },
  { "harf_sayisi": 8, "soru": "Bir dilin lehçesi", "cevap": "DİYALEKT" },
  { "harf_sayisi": 8, "soru": "Bir dilin yöresel ağzı", "cevap": "DİYALEKT" },
  { "harf_sayisi": 8, "soru": "Bir filmi veya tiyatro oyununu yöneten kişi", "cevap": "YÖNETMEN" },
  { "harf_sayisi": 8, "soru": "Bir kişinin kendine özgü yapısı, kişiliği", "cevap": "KARAKTER" },
  { "harf_sayisi": 8, "soru": "Bir şeyin daha iyi duruma getirilmesi", "cevap": "İLERLEME" },
  { "harf_sayisi": 8, "soru": "Bir yarışmada birinci olan kişi veya takım", "cevap": "ŞAMPİYON" },
  { "harf_sayisi": 8, "soru": "Devlet yönetme bilimi", "cevap": "POLİTİKA" },
  { "harf_sayisi": 8, "soru": "Diğer bir İstanbul takımı", "cevap": "BEŞİKTAŞ" },
  { "harf_sayisi": 8, "soru": "Dizelerin ilk harflerinin yukarıdan aşağıya anlamlı bir sözcük oluşturduğu şiir türü", "cevap": "AKROSTİŞ" },
  { "harf_sayisi": 8, "soru": "Dünyayı fetheden padişah", "cevap": "CİHANGİR" },
  { "harf_sayisi": 8, "soru": "Düşünce yoluyla iletişim kurma", "cevap": "TELEPATİ" },
  { "harf_sayisi": 8, "soru": "Edebiyatta abartma sanatı", "cevap": "HİPERBOL" },
  { "harf_sayisi": 8, "soru": "Ev işlerinde yardımcı", "cevap": "HİZMETÇİ" },
  { "harf_sayisi": 8, "soru": "Farklı kaynaklardan alınmış unsurları birleştiren (felsefe, sanat)", "cevap": "EKLEKTİK" },
  { "harf_sayisi": 8, "soru": "Genel ağ", "cevap": "İNTERNET" },
  { "harf_sayisi": 8, "soru": "Genel bir doğruyu özlü bir şekilde anlatan söz", "cevap": "AFORİZMA" },
  { "harf_sayisi": 8, "soru": "Göz aldanması", "cevap": "İLLÜZYON" },
  { "harf_sayisi": 8, "soru": "Güvence parası", "cevap": "DEPOZİTO" },
  { "harf_sayisi": 8, "soru": "Güzel kokulu bir çiçek", "cevap": "HANIMELİ" },
  { "harf_sayisi": 8, "soru": "Haber toplayan ve yayan kişi", "cevap": "GAZETECİ" },
  { "harf_sayisi": 8, "soru": "Haberleşme, bildirişim", "cevap": "İLETİŞİM" },
  { "harf_sayisi": 8, "soru": "Işıkla resim çizme sanatı", "cevap": "FOTOĞRAF" },
  { "harf_sayisi": 8, "soru": "İhbar eden, gammaz", "cevap": "JURNALCİ" },
  { "harf_sayisi": 8, "soru": "Kakaolu bir tatlı", "cevap": "ÇİKOLATA" },
  { "harf_sayisi": 8, "soru": "Karmaşık yollar", "cevap": "LABİRENT" },
  { "harf_sayisi": 8, "soru": "Kırsal kesimde güvenliği sağlayan kolluk kuvveti", "cevap": "JANDARMA" },
  { "harf_sayisi": 8, "soru": "Oyun kağıdı", "cevap": "İSKAMBİL" },
  { "harf_sayisi": 8, "soru": "Pedallı ulaşım aracı", "cevap": "BİSİKLET" },
  { "harf_sayisi": 8, "soru": "Pembe, uzun bacaklı bir kuş", "cevap": "FLAMİNGO" },
  { "harf_sayisi": 8, "soru": "Resmi belgeleri onaylayan görevli", "cevap": "NOTERLİK" },
  { "harf_sayisi": 8, "soru": "Sınıflandırma, bölüm", "cevap": "KATEGORİ" },
  { "harf_sayisi": 8, "soru": "Solunum kası", "cevap": "DİYAFRAM" },
  { "harf_sayisi": 8, "soru": "Sporcu çalıştırıcısı", "cevap": "ANTRENÖR" },
  { "harf_sayisi": 8, "soru": "Suçluyu bulmaya çalışan görevli", "cevap": "DEDEKTİF" },
  { "harf_sayisi": 8, "soru": "Tercüman", "cevap": "MÜTERCİM" }, // Düzeltildi: ÇEVİRMEN 8 harfliydi
  { "harf_sayisi": 8, "soru": "Tren garı", "cevap": "İSTASYON" },
  { "harf_sayisi": 8, "soru": "Tren sürücüsü", "cevap": "MAKİNİST" },
  { "harf_sayisi": 8, "soru": "Un öğüten yapı", "cevap": "DEĞİRMEN" },
  { "harf_sayisi": 8, "soru": "Üniversitede en yüksek rütbeli öğretim üyesi", "cevap": "PROFESÖR" },
  { "harf_sayisi": 8, "soru": "Yazı ve şiir sanatı", "cevap": "EDEBİYAT" },
  { "harf_sayisi": 8, "soru": "Yazının bir bölümü", "cevap": "PARAGRAF" },
  { "harf_sayisi": 8, "soru": "Yolcu taşıyan büyük tekerlekli araç", "cevap": "OTOMOBİL" },
  { "harf_sayisi": 8, "soru": "Yönetici yardımcısı, yazman", "cevap": "SEKRETER" },
  { "harf_sayisi": 9, "soru": "Bilgelik üzerine kurulu felsefi düşünce", "cevap": "HİKEMİYAT" },
  { "harf_sayisi": 9, "soru": "Bir ağaç türü", "cevap": "OKALİPTÜS" },
  { "harf_sayisi": 9, "soru": "Bir konu hakkında yazılmış bilimsel eser", "cevap": "MONOGRAFİ" },
  { "harf_sayisi": 9, "soru": "Bir sayının, başka bir sayı tabanına göre üssünü veren matematiksel fonksiyon", "cevap": "LOGARİTMA" },
  { "harf_sayisi": 9, "soru": "Bir şeyin doğruluğunu kanıtlayan belge", "cevap": "SERTİFİKA" },
  { "harf_sayisi": 9, "soru": "Bir şeyin nasıl çalıştığını gösteren düzenek", "cevap": "MEKANİZMA" },
  { "harf_sayisi": 9, "soru": "Bir ülkenin başka bir ülkede bulunan temsilciliği", "cevap": "BÜYÜKELÇİ" }, 
  { "harf_sayisi": 9, "soru": "Bir yarışmaya katılan kişi", "cevap": "YARIŞMACI" }, 
  { "harf_sayisi": 9, "soru": "Bir yeri görmeye giden kişi", "cevap": "ZİYARETÇİ" },
  { "harf_sayisi": 9, "soru": "Birlikte çalışma", "cevap": "İŞBİRLİĞİ" },
  { "harf_sayisi": 9, "soru": "Canlıların işlevlerini inceleyen bilim", "cevap": "FİZYOLOJİ" },
  { "harf_sayisi": 9, "soru": "Canlıların kimyasal yapısını inceleyen bilim dalı", "cevap": "BİYOKİMYA" },
  { "harf_sayisi": 9, "soru": "Çok küçük nesneleri büyüten alet", "cevap": "MİKROSKOP" },
  { "harf_sayisi": 9, "soru": "Dans adımlarını ve figürlerini tasarlayan sanatçı", "cevap": "KOREOGRAF" },
  { "harf_sayisi": 9, "soru": "Denizin altında giden gemi", "cevap": "DENİZALTI" },
  { "harf_sayisi": 9, "soru": "Dik üçgende en uzun kenar", "cevap": "HİPOTENÜS" },
  { "harf_sayisi": 9, "soru": "Ekonomide tarımın tek verimli alan olduğunu savunan öğreti", "cevap": "FİZYOKRAT" },
  { "harf_sayisi": 9, "soru": "El ustalığı gerektiren işleri yapan kişi", "cevap": "ZANAATKAR" },
  { "harf_sayisi": 9, "soru": "Elektrik üreten büyük makine", "cevap": "JENERATÖR" },
  { "harf_sayisi": 9, "soru": "Felsefenin, varlığın ve bilginin ilk nedenleriyle ilgilenen dalı", "cevap": "METAFİZİK" },
  { "harf_sayisi": 9, "soru": "Hafif bir metal", "cevap": "ALÜMİNYUM" },
  { "harf_sayisi": 9, "soru": "Harflerin sırasıyla ilgili", "cevap": "ALFABETİK" },
  { "harf_sayisi": 9, "soru": "Isıtma sistemi", "cevap": "KALORİFER" },
  { "harf_sayisi": 9, "soru": "Kalp ve akciğer seslerini dinleme aleti", "cevap": "STETESKOP" },
  { "harf_sayisi": 9, "soru": "Kendi kendine yemek alınan lokanta", "cevap": "KAFETERYA" },
  { "harf_sayisi": 9, "soru": "Kitapların bulunduğu yer", "cevap": "KÜTÜPHANE" },
  { "harf_sayisi": 9, "soru": "Kurşun kalemle yapılan çizim", "cevap": "KARAKALEM" },
  { "harf_sayisi": 9, "soru": "Paranın değer kaybetmesiyle fiyatların genel düzeyinin sürekli artması", "cevap": "ENFLASYON" },
  { "harf_sayisi": 9, "soru": "Sayılarla ilgilenen bilim dalı", "cevap": "MATEMATİK" }, 
  { "harf_sayisi": 9, "soru": "Senfoni orkestrası", "cevap": "FİLARMONİ" },
  { "harf_sayisi": 9, "soru": "Tren vagonlarını çeken araç", "cevap": "LOKOMOTİF" },
  { "harf_sayisi": 9, "soru": "Turunçgil bir meyve", "cevap": "MANDALİNA" },
  { "harf_sayisi": 9, "soru": "Uygulamalı bilim", "cevap": "TEKNOLOJİ" },
  { "harf_sayisi": 9, "soru": "Vücudun içini görüntüleme yöntemi", "cevap": "ENDOSKOPİ" },
  { "harf_sayisi": 9, "soru": "Yaşam öyküsü", "cevap": "BİYOGRAFİ" },
  { "harf_sayisi": 9, "soru": "Yazışmaları yürüten görevli", "cevap": "YAZIŞMACI" },
  { "harf_sayisi": 9, "soru": "Yer altı sıcak su kaynakları", "cevap": "JEOTERMAL" }, 
  { "harf_sayisi": 9, "soru": "Yetenek", "cevap": "KABİLİYET" },
  { "harf_sayisi": 9, "soru": "Yol gösterme, danışmanlık", "cevap": "REHBERLİK" },
  { "harf_sayisi": 10, "soru": "Antik Mısır'ın resim yazısı", "cevap": "HİYEROGLİF" },
  { "harf_sayisi": 10, "soru": "Aracın yönünü belirleyen düzenek", "cevap": "DİREKSİYON" },
  { "harf_sayisi": 10, "soru": "Bilgisayar bilimiyle ilgili", "cevap": "ELEKTRONİK" },
  { "harf_sayisi": 10, "soru": "Bir ilacın kullanım kılavuzu", "cevap": "PROSPEKTÜS" },
  { "harf_sayisi": 10, "soru": "Bir İstanbul takımı", "cevap": "FENERBAHÇE" },
  { "harf_sayisi": 10, "soru": "Bir kişiyi belirli bir amaca doğru harekete geçiren içsel güç, güdülenme", "cevap": "MOTİVASYON" },
  { "harf_sayisi": 10, "soru": "Bir sanatçının veya sporcunun işlerini yönetme mesleği", "cevap": "MENAJERLİK" },
  { "harf_sayisi": 10, "soru": "Bitkilerin güneş enerjisiyle besin üretmesi", "cevap": "FOTOSENTEZ" },
  { "harf_sayisi": 10, "soru": "Büyüklük kuruntusu veya kendini aşırı büyük görme durumu", "cevap": "MEGALOMANİ" },
  { "harf_sayisi": 10, "soru": "Dans adımlarını tasarlayan sanat", "cevap": "KOREOGRAFİ" },
  { "harf_sayisi": 10, "soru": "Deney yapılan yer", "cevap": "LABORATUAR" },
  { "harf_sayisi": 10, "soru": "Eş zamanlı, aynı anda gerçekleşen", "cevap": "SENKRONİZE" },
  { "harf_sayisi": 10, "soru": "Görüntü ve ses yayını yapan kutu", "cevap": "TELEVİZYON" },
  { "harf_sayisi": 10, "soru": "Halkın kendi kendini yönetmesi", "cevap": "CUMHURİYET" }, 
  { "harf_sayisi": 10, "soru": "Hatay'ın bir ilçesi", "cevap": "İSKENDERUN" },
  { "harf_sayisi": 10, "soru": "Hava akımı yaratarak serinletmeye yarayan pervane", "cevap": "VANTİLATÖR" },
  { "harf_sayisi": 10, "soru": "İleri görüşlü planlar yapan, taktik uzmanı", "cevap": "STRATEJİST" },
  { "harf_sayisi": 10, "soru": "İnsanın kökenini ve kültürel özelliklerini inceleyen bilim insanı", "cevap": "ANTROPOLOG" },
  { "harf_sayisi": 10, "soru": "Kavramsal, bir düşünce veya kavrama dayalı (sanat, felsefe)", "cevap": "KONSEPTÜEL" },
  { "harf_sayisi": 10, "soru": "Kışkırtıcı, toplulukları yasa dışı davranışlara iten kimse", "cevap": "PROVOKATÖR" },
  { "harf_sayisi": 10, "soru": "Kuralları belirleyen yazılı belge", "cevap": "YÖNETMELİK" },
  { "harf_sayisi": 10, "soru": "Milletvekillerinin toplandığı meclis", "cevap": "PARLAMENTO" },
  { "harf_sayisi": 10, "soru": "Motor parçası", "cevap": "KARBÜRATÖR" },
  { "harf_sayisi": 10, "soru": "Müziği bilimsel olarak inceleyen disiplin", "cevap": "MÜZİKOLOJİ" },
  { "harf_sayisi": 10, "soru": "Müzik besteleyen sanatçı", "cevap": "KOMPOZİTÖR" },
  { "harf_sayisi": 10, "soru": "Osmanlı Padişahı", "cevap": "ABDÜLHAMİT" },
  { "harf_sayisi": 10, "soru": "Para çekme makinesi", "cevap": "BANKAMATİK" },
  { "harf_sayisi": 10, "soru": "Pervaneli hava taşıtı", "cevap": "HELİKOPTER" },
  { "harf_sayisi": 10, "soru": "Sınıflandırmak, bölümlere ayırmak eylemi", "cevap": "KATEGORİZE" },
  { "harf_sayisi": 10, "soru": "Sinir sistemi hastalıklarıyla ilgilenen tıp dalı", "cevap": "SİNİRBİLİM" }, 
  { "harf_sayisi": 10, "soru": "Şirket içi hiyerarşi şeması", "cevap": "ORGANİGRAM" },
  { "harf_sayisi": 10, "soru": "Türkiye'nin yönetim şekli", "cevap": "CUMHURİYET" },
  { "harf_sayisi": 10, "soru": "Üretim araçlarının özel mülkiyete dayandığı ekonomik sistem", "cevap": "KAPİTALİZM" },
  { "harf_sayisi": 10, "soru": "Veri bilimi", "cevap": "İSTATİSTİK" },
  { "harf_sayisi": 10, "soru": "Veri işleyen elektronik cihaz", "cevap": "BİLGİSAYAR" },
  { "harf_sayisi": 10, "soru": "Vücut sıcaklığını ölçen alet", "cevap": "TERMOMETRE" },
  { "harf_sayisi": 10, "soru": "Yaklaşık olarak aynı yıllarda doğmuş insanlar topluluğu, kuşak", "cevap": "JENERASYON" },
  { "harf_sayisi": 10, "soru": "Yemek kültürü ve sanatı", "cevap": "GASTRONOMİ" },
  { "harf_sayisi": 10, "soru": "Yükseköğrenim kurumu", "cevap": "ÜNİVERSİTE" }
];







