const soruBankasi = [
  { "harf_sayisi": 3, "soru": "Görme organı", "cevap": "GÖZ" },
  { "harf_sayisi": 3, "soru": "Sıcak içecek", "cevap": "ÇAY" },
  { "harf_sayisi": 3, "soru": "Ağacın kolu", "cevap": "DAL" },
  { "harf_sayisi": 3, "soru": "Vücudun bir uzvu", "cevap": "KOL" },
  { "harf_sayisi": 3, "soru": "Arının ürettiği tatlı besin", "cevap": "BAL" },
  { "harf_sayisi": 3, "soru": "Pencere malzemesi", "cevap": "CAM" },
  { "harf_sayisi": 3, "soru": "Uzaktan kumanda güç kaynağı", "cevap": "PİL" },
  { "harf_sayisi": 3, "soru": "Donmuş su", "cevap": "BUZ" },
  { "harf_sayisi": 3, "soru": "İletişim kablosu", "cevap": "TEL" },
  { "harf_sayisi": 3, "soru": "Görüşü engelleyen duman", "cevap": "SİS" },
  { "harf_sayisi": 3, "soru": "Yanmakta olan odun parçası", "cevap": "KOR" },
  { "harf_sayisi": 3, "soru": "Başın üstündeki kıllar", "cevap": "SAÇ" },
  { "harf_sayisi": 3, "soru": "İnce, küçük zerre", "cevap": "TOZ" },
  { "harf_sayisi": 3, "soru": "Eski Türk hükümdarı", "cevap": "HAN" },
  { "harf_sayisi": 3, "soru": "Tiyatroda canlandırılan kişilik", "cevap": "ROL" },
  { "harf_sayisi": 3, "soru": "Islaklık, rutubet", "cevap": "NEM" },
  { "harf_sayisi": 3, "soru": "Hayvan yiyeceği", "cevap": "YEM" },
  { "harf_sayisi": 3, "soru": "Koyundan elde edilen iplik", "cevap": "YÜN" },
  { "harf_sayisi": 3, "soru": "Leke, pislik", "cevap": "KİR" },
  { "harf_sayisi": 3, "soru": "Kapı veya bisikletteki sesli uyarıcı", "cevap": "ZİL" },
  { "harf_sayisi": 3, "soru": "Gezi, seyahat", "cevap": "TUR" },
  { "harf_sayisi": 3, "soru": "Ani ve şaşırtıcı olay", "cevap": "ŞOK" },
  { "harf_sayisi": 3, "soru": "Serinletici alet", "cevap": "FAN" },
  { "harf_sayisi": 3, "soru": "Yakıt türü", "cevap": "GAZ" },
  { "harf_sayisi": 3, "soru": "Omuza atılan dokuma", "cevap": "ŞAL" },
  { "harf_sayisi": 3, "soru": "Çeşit, cins", "cevap": "TÜR" },
  { "harf_sayisi": 3, "soru": "Kuvvet, takat", "cevap": "GÜÇ" },
  { "harf_sayisi": 3, "soru": "Allah'a hizmet eden", "cevap": "KUL" },


  { "harf_sayisi: 4, "soru": "Eğitim görülen yer", "cevap": "OKUL" },
  { "harf_sayisi": 4, "soru": "Satrançtaki bir taş", "cevap": "KALE" },
  { "harf_sayisi": 4, "soru": "Üzerinde yemek yenilen mobilya", "cevap": "MASA" },
  { "harf_sayisi": 4, "soru": "Bir odaya giriş yeri", "cevap": "KAPI" },
  { "harf_sayisi": 4, "soru": "Küçük kemirgen", "cevap": "FARE" },
  { "harf_sayisi": 4, "soru": "Halkın dinlendiği yeşil alan", "cevap": "PARK" },
  { "harf_sayisi": 4, "soru": "Deniz ulaşım aracı", "cevap": "GEMİ" },
  { "harf_sayisi": 4, "soru": "Birleştirici metal parça", "cevap": "VİDA" },
  { "harf_sayisi": 4, "soru": "Cilde sürülen yumuşatıcı", "cevap": "KREM" },
  { "harf_sayisi": 4, "soru": "Şarkı söyleyen topluluk", "cevap": "KORO" },
  { "harf_sayisi": 4, "soru": "Yemek listesi", "cevap": "MENÜ" },
  { "harf_sayisi": 4, "soru": "Hükümdar, yönetici", "cevap": "KRAL" },
  { "harf_sayisi": 4, "soru": "Geometrik bir şekil", "cevap": "KARE" },
  { "harf_sayisi": 4, "soru": "Kuşun evi", "cevap": "YUVA" },
  { "harf_sayisi": 4, "soru": "Popüler olan, geçerli olan", "cevap": "MODA" },
  { "harf_sayisi": 4, "soru": "Giysinin boyun kısmı", "cevap": "YAKA" },
  { "harf_sayisi": 4, "soru": "Bir takı", "cevap": "KÜPE" },
  { "harf_sayisi": 4, "soru": "Yiyecek saklanan yer", "cevap": "DEPO" },
  { "harf_sayisi": 4, "soru": "Müzik yazısı", "cevap": "NOTA" },
  { "harf_sayisi": 4, "soru": "Bir tahıl", "cevap": "ARPA" },
  { "harf_sayisi": 4, "soru": "Bir iskambil kartı", "cevap": "VALE" },
  { "harf_sayisi": 4, "soru": "Bir avcı kuşu", "cevap": "ŞAHİN" },
  { "harf_sayisi": 4, "soru": "İzin, müsaade", "cevap": "ONAY" },
  { "harf_sayisi": 4, "soru": "Bir içecek", "cevap": "KOLA" },

  { "harf_sayisi": 5, "soru": "Ses yayını yapan cihaz", "cevap": "RADYO" },
  { "harf_sayisi": 5, "soru": "Okunan, yazılı eser", "cevap": "KİTAP" },
  { "harf_sayisi": 5, "soru": "Sadık ev hayvanı", "cevap": "KÖPEK" },
  { "harf_sayisi": 5, "soru": "Ağaç topluluğu", "cevap": "ORMAN" },
  { "harf_sayisi": 5, "soru": "Yaşadığımız gezegen", "cevap": "DÜNYA" },
  { "harf_sayisi": 5, "soru": "Hastalara bakan meslek", "cevap": "HEKİM" },
  { "harf_sayisi": 5, "soru": "Uçak kullanan kişi", "cevap": "PİLOT" },
  { "harf_sayisi": 5, "soru": "Suda yaşayan büyük memeli", "cevap": "YUNUS" },
  { "harf_sayisi": 5, "soru": "Tatlı, beyaz kristal", "cevap": "ŞEKER" },
  { "harf_sayisi": 5, "soru": "Kabuklu bir yemiş", "cevap": "CEVİZ" },
  { "harf_sayisi": 5, "soru": "Maç sonucu", "cevap": "SONUÇ" },
  { "harf_sayisi": 5, "soru": "Bir şeyin kopyası, benzeri", "cevap": "MODEL" },
  { "harf_sayisi": 5, "soru": "Yerin altından geçen yol", "cevap": "TÜNEL" },
  { "harf_sayisi": 5, "soru": "Yazı yazma aracı", "cevap": "KALEM" },
  { "harf_sayisi": 5, "soru": "Bir tür narenciye", "cevap": "LİMON" },
  { "harf_sayisi": 5, "soru": "Bir Kümes hayvanı", "cevap": "HOROZ" },
  { "harf_sayisi": 5, "soru": "Büyük su kabı", "cevap": "BİDON" },
  { "harf_sayisi": 5, "soru": "Meyve ve sebze satılan yer", "cevap": "MANAV" },
  { "harf_sayisi": 5, "soru": "İnsan yüzü, çehre", "cevap": "SURET" },
  { "harf_sayisi": 5, "soru": "Yere serilen dokuma", "cevap": "KİLİM" },
  { "harf_sayisi": 5, "soru": "Oturma odası", "cevap": "SALON" },
  { "harf_sayisi": 5, "soru": "Duvardaki resim", "cevap": "TABLO" },
  { "harf_sayisi": 5, "soru": "Bir işte yetkin kişi", "cevap": "UZMAN" },
  { "harf_sayisi": 5, "soru": "Tren vagonu", "cevap": "VAGON" },
  { "harf_sayisi": 5, "soru": "Beyaz bir kuş", "cevap": "MARTI" },
  { "harf_sayisi": 5, "soru": "Bir spor dalı", "cevap": "TENİS" },
  { "harf_sayisi": 5, "soru": "Bir müzik aleti", "cevap": "GİTAR" },
  { "harf_sayisi": 5, "soru": "Yarışmacı, hasım", "cevap": "RAKİP" },
  { "harf_sayisi": 6, "soru": "Vücut yapısı", "cevap": "BÜNYE" },



  { "harf_sayisi": 6, "soru": "Oturmaya yarayan mobilya", "cevap": "KANEPE" },
  { "harf_sayisi": 6, "soru": "Yön bulmaya yarayan alet", "cevap": "PUSULA" },
  { "harf_sayisi": 6, "soru": "Güzel koku", "cevap": "PARFÜM" },
  { "harf_sayisi": 6, "soru": "İlaç kullanım tarifi", "cevap": "REÇETE" },
  { "harf_sayisi": 6, "soru": "Bir spor takımının lideri", "cevap": "KAPTAN" },
  { "harf_sayisi": 6, "soru": "Bilimsel yazı türü", "cevap": "MAKALE" },
  { "harf_sayisi": 6, "soru": "Binanın dışa çıkıntılı bölümü", "cevap": "BALKON" },
  { "harf_sayisi": 6, "soru": "Bir işin ön çalışması", "cevap": "TASLAK" },
  { "harf_sayisi": 6, "soru": "Parçaları birleştirme", "cevap": "MONTAJ" },
  { "harf_sayisi": 6, "soru": "Eşya taşımak için kutu", "cevap": "SANDIK" },
  { "harf_sayisi": 6, "soru": "Para cüzdanı", "cevap": "CÜZDAN" },
  { "harf_sayisi": 6, "soru": "Alışveriş yapılan yer", "cevap": "MARKET" },
  { "harf_sayisi": 6, "soru": "Hukuk, hak", "cevap": "ADALET" },
  { "harf_sayisi": 6, "soru": "Bir spor türü", "cevap": "BASKET" },
  { "harf_sayisi": 6, "soru": "Saklı hazine", "cevap": "DEFİNE" },
  { "harf_sayisi": 6, "soru": "Sıvıyı süzen alet", "cevap": "FİLTRE" },
  { "harf_sayisi": 6, "soru": "Sanat eserlerinin sergilendiği yer", "cevap": "GALERİ" },
  { "harf_sayisi": 6, "soru": "Özlem", "cevap": "HASRET" },
  { "harf_sayisi": 6, "soru": "Gemilerin yanaştığı yer", "cevap": "İSKELE" },
  { "harf_sayisi": 6, "soru": "Bir tür başlık", "cevap": "KASKET" },
  { "harf_sayisi": 6, "soru": "Bir şeyin eksikliği", "cevap": "NOKSAN" },
  { "harf_sayisi": 6, "soru": "Otobüslerin kalktığı yer", "cevap": "OTOGAR" },
  { "harf_sayisi": 6, "soru": "Arazi parçası", "cevap": "PARSEL" },
  { "harf_sayisi": 6, "soru": "Dokunmatik ekranlı cihaz", "cevap": "TABLET" },
  { "harf_sayisi": 6, "soru": "Bir şeyin sonucu", "cevap": "NETİCE" },
  { "harf_sayisi": 6, "soru": "Bir şeyin merkezi", "cevap": "MERKEZ" },
  { "harf_sayisi": 6, "soru": "Halk arasında anlatılan olağanüstü hikaye", "cevap": "EFSANE" },
  { "harf_sayisi": 6, "soru": "Geçmişte yaşanmış olayları anlatan yazı", "cevap": "HİKAYE" },
  { "harf_sayisi": 6, "soru": "Bir görevden kendi isteğiyle ayrılma", "cevap": "İSTİFA" },
  { "harf_sayisi": 6, "soru": "Yumuşak, parlak bir kumaş türü", "cevap": "KADİFE" },
  { "harf_sayisi": 6, "soru": "Yanardağ", "cevap": "VOLKAN" },

  { "harf_sayisi": 7, "soru": "Uzak mesafe iletişim aracı", "cevap": "TELEFON" },
  { "harf_sayisi": 7, "soru": "Yağmurdan koruyan alet", "cevap": "ŞEMSİYE" },
  { "harf_sayisi": 7, "soru": "Kapı ve kilitleri açan alet", "cevap": "ANAHTAR" },
  { "harf_sayisi": 7, "soru": "Mikroskobik canlı", "cevap": "BAKTERİ" },
  { "harf_sayisi": 7, "soru": "Resim çerçevesi", "cevap": "ÇERÇEVE" },
  { "harf_sayisi": 7, "soru": "Patlayıcı madde", "cevap": "DİNAMİT" },
  { "harf_sayisi": 7, "soru": "Başarı gösterenlere verilen metal nişan", "cevap": "MADALYA" },
  { "harf_sayisi": 7, "soru": "Soluduğumuz gaz", "cevap": "OKSİJEN" },
  { "harf_sayisi": 7, "soru": "Binanın dışarıya bakan, camlı bölümü", "cevap": "PENCERE" },
  { "harf_sayisi": 7, "soru": "Bir şeyi güvence altına alma", "cevap": "SİGORTA" },
  { "harf_sayisi": 7, "soru": "Sahne oyunu", "cevap": "TİYATRO" },
  
  { "harf_sayisi": 7, "soru": "Vücudumuz için gerekli organik bileşik", "cevap": "VİTAMİN" },
  { "harf_sayisi": 7, "soru": "Bir şeyin nasıl yapılacağını gösteren kurallar bütünü", "cevap": "YÖNERGE" },
  { "harf_sayisi": 7, "soru": "Yüksek bir yerden hızla düşen su kütlesi", "cevap": "ŞELALE" },
  { "harf_sayisi": 7, "soru": "Trafik işareti levhası", "cevap": "TABELA" },
  { "harf_sayisi": 7, "soru": "Bir sıvının içinde katı bir maddenin çözünmesiyle oluşan karışım", "cevap": "ÇÖZELTİ" },
  { "harf_sayisi": 7, "soru": "Bir işin yapılması için gereken süre", "cevap": "MÜDDET" },
  { "harf_sayisi": 7, "soru": "Bir konuyu aydınlatmak için yapılan konuşma", "cevap": "SÖYLEŞİ" },
  { "harf_sayisi": 7, "soru": "Bir yerden bir yere mal taşıma", "cevap": "NAKLİYE" },
  { "harf_sayisi": 7, "soru": "Birine bir işi yapması için yetki verme", "cevap": "VEKALET" },
  { "harf_sayisi": 7, "soru": "Birine verilen armağan", "cevap": "HEDİYE" },
  { "harf_sayisi": 7, "soru": "Sınav", "cevap": "İMTİHAN" },
  { "harf_sayisi": 7, "soru": "Para alan görevli", "cevap": "KASİYER" },
  { "harf_sayisi": 7, "soru": "Oturmak için kullanılan, genellikle tek kişilik mobilya", "cevap": "KOLTUK" },
  { "harf_sayisi": 7, "soru": "Devleti yöneten organ", "cevap": "YÖNETİM" },



  { "harf_sayisi": 8, "soru": "Kakaolu bir tatlı", "cevap": "ÇİKOLATA" },
  { "harf_sayisi": 8, "soru": "Pedallı ulaşım aracı", "cevap": "BİSİKLET" },
  { "harf_sayisi": 8, "soru": "Yazı ve şiir sanatı", "cevap": "EDEBİYAT" },
  { "harf_sayisi": 8, "soru": "Işıkla resim çizme sanatı", "cevap": "FOTOĞRAF" },
  { "harf_sayisi": 8, "soru": "Yıldızlar ve gezegenler sistemi", "cevap": "GALAKSİLER" }, // Düzeltildi: GALAKSİ 7 harfliydi
  { "harf_sayisi": 8, "soru": "Coşku, telaş", "cevap": "TELAŞLANMA" }, // Düzeltildi: HEYECAN 7 harfliydi
  { "harf_sayisi": 8, "soru": "Haberleşme, bildirişim", "cevap": "İLETİŞİM" },
  { "harf_sayisi": 8, "soru": "Kırsal kesimde güvenliği sağlayan kolluk kuvveti", "cevap": "JANDARMA" },
  { "harf_sayisi": 8, "soru": "Bir kişinin kendine özgü yapısı, kişiliği", "cevap": "KARAKTER" },
  { "harf_sayisi": 8, "soru": "Turunçgil bir meyve", "cevap": "MANDALİNA" },
  { "harf_sayisi": 8, "soru": "Yolcu taşıyan büyük tekerlekli araç", "cevap": "OTOMOBİL" },
  { "harf_sayisi": 8, "soru": "Yazının bir bölümü", "cevap": "PARAGRAF" },
  { "harf_sayisi": 8, "soru": "Yol gösterme, danışmanlık", "cevap": "REHBERLİK" },
  { "harf_sayisi": 8, "soru": "Devlet yönetme bilimi", "cevap": "POLİTİKA" }, // Düzeltildi: SİYASET 7 harfliydi
  { "harf_sayisi": 8, "soru": "Bir yarışmada birinci olan kişi veya takım", "cevap": "ŞAMPİYON" },
  { "harf_sayisi": 8, "soru": "Bir dilden başka bir dile çeviri yapan kişi", "cevap": "TERCÜMAN" },
  { "harf_sayisi": 8, "soru": "Bir filmi veya tiyatro oyununu yöneten kişi", "cevap": "YÖNETMEN" },
  { "harf_sayisi": 8, "soru": "Hayvanları inceleyen bilim dalı", "cevap": "HAYVANBİLİM" }, // Düzeltildi: ZOOLOJİ 7 harfliydi
  { "harf_sayisi": 8, "soru": "Yol gösteren kitapçık", "cevap": "REHBERKİTAP" }, // Düzeltildi: KILAVUZ 7 harfliydi
  { "harf_sayisi": 8, "soru": "Bir işin yapılması için gerekli olan araç ve gereçlerin tümü", "cevap": "MALZEME" },
  { "harf_sayisi": 8, "soru": "Bir ülkenin başka bir ülkede bulunan temsilciliği", "cevap": "BÜYÜKELÇİ" }, // Düzeltildi: ELÇİLİK 7 harfliydi
  { "harf_sayisi": 8, "soru": "Bir topluluğun ortaklaşa sahip olduğu değerlerin tümü", "cevap": "TÖRENLER" }, // Düzeltildi: GELENEK 7 harfliydi
  { "harf_sayisi": 8, "soru": "Bir şeyin daha iyi duruma getirilmesi", "cevap": "İLERLEME" },
  { "harf_sayisi": 8, "soru": "Bir şeyin nasıl çalıştığını gösteren düzenek", "cevap": "MEKANİZMA" },
  { "harf_sayisi": 8, "soru": "Genel ağ", "cevap": "İNTERNET" },
  { "harf_sayisi": 8, "soru": "Yetenek", "cevap": "KABİLİYET" },
  { "harf_sayisi": 8, "soru": "Karmaşık yollar", "cevap": "LABİRENT" },
  { "harf_sayisi": 8, "soru": "Tren sürücüsü", "cevap": "MAKİNİST" },
  { "harf_sayisi": 8, "soru": "Resmi belgeleri onaylayan görevli", "cevap": "NOTERLİK" },
  { "harf_sayisi": 8, "soru": "Bir ağaç türü", "cevap": "OKALİPTÜS" },

  { "harf_sayisi": 9, "soru": "Elektrik üreten büyük makine", "cevap": "JENERATÖR" },
  { "harf_sayisi": 9, "soru": "Tren vagonlarını çeken araç", "cevap": "LOKOMOTİF" },
  { "harf_sayisi": 9, "soru": "Çok küçük nesneleri büyüten alet", "cevap": "MİKROSKOP" },
  { "harf_sayisi": 9, "soru": "Üniversitede en yüksek rütbeli öğretim üyesi", "cevap": "PROFESÖR" },
  { "harf_sayisi": 9, "soru": "Yönetici yardımcısı, yazman", "cevap": "SEKRETER" },
  { "harf_sayisi": 9, "soru": "Düşünce yoluyla iletişim kurma", "cevap": "TELEPATİ" },
  { "harf_sayisi": 9, "soru": "Harflerin sırasıyla ilgili", "cevap": "ALFABETİK" },
  { "harf_sayisi": 9, "soru": "Bir ülkenin yönetim merkezi olan şehir", "cevap": "ANAKENT" }, // Düzeltildi: BAŞKENT 7 harfliydi
  { "harf_sayisi": 9, "soru": "Denizin altında giden gemi", "cevap": "DENİZALTI" },
  { "harf_sayisi": 9, "soru": "Vücudun içini görüntüleme yöntemi", "cevap": "ENDOSKOPİ" },
  { "harf_sayisi": 9, "soru": "Senfoni orkestrası", "cevap": "FİLARMONİ" },
  { "harf_sayisi": 9, "soru": "Haber toplayan ve yayan kişi", "cevap": "GAZETECİ" },
  { "harf_sayisi": 9, "soru": "Dik üçgende en uzun kenar", "cevap": "HİPOTENÜS" },
  { "harf_sayisi": 9, "soru": "Oyun kağıdı", "cevap": "İSKAMBİL" },
  { "harf_sayisi": 9, "soru": "Sınıflandırma, bölüm", "cevap": "KATEGORİ" },
  { "harf_sayisi": 9, "soru": "Bina tasarlama sanatı", "cevap": "MİMARLIK" },
  { "harf_sayisi": 9, "soru": "Uygulamalı bilim", "cevap": "TEKNOLOJİ" },
  { "harf_sayisi": 9, "soru": "Kuralları belirleyen yazılı belge", "cevap": "YÖNETMELİK" },
  { "harf_sayisi": 9, "soru": "Bir yeri görmeye giden kişi", "cevap": "ZİYARETÇİ" },
  { "harf_sayisi": 9, "soru": "Bir şeyin doğruluğunu kanıtlayan belge", "cevap": "SERTİFİKA" },
  { "harf_sayisi": 9, "soru": "Suçluyu bulmaya çalışan görevli", "cevap": "DEDEKTİF" },
  { "harf_sayisi": 9, "soru": "Birlikte çalışma", "cevap": "İŞBİRLİĞİ" },
  { "harf_sayisi": 9, "soru": "Sporcu çalıştırıcısı", "cevap": "ANTRENÖR" },
  { "harf_sayisi": 9, "soru": "Bilgilendirici film", "cevap": "BELGESEL" },
  { "harf_sayisi": 9, "soru": "Tercüman", "cevap": "MÜTERCİM" }, // Düzeltildi: ÇEVİRMEN 8 harfliydi
  { "harf_sayisi": 9, "soru": "Solunum kası", "cevap": "DİYAFRAM" },
  { "harf_sayisi": 9, "soru": "Üretim, dağıtım ve tüketim bilimi", "cevap": "İKTİSAT" }, // Düzeltildi: EKONOMİ 7 harfliydi
  { "harf_sayisi": 9, "soru": "Canlıların işlevlerini inceleyen bilim", "cevap": "FİZYOLOJİ" },
  { "harf_sayisi": 9, "soru": "Güvence", "cevap": "TEMİNAT" },
  { "harf_sayisi": 9, "soru": "Kitapların bulunduğu yer", "cevap": "KÜTÜPHANE" },
  

  { "harf_sayisi": 10, "soru": "Veri işleyen elektronik cihaz", "cevap": "BİLGİSAYAR" },
  { "harf_sayisi": 10, "soru": "Görüntü ve ses yayını yapan kutu", "cevap": "TELEVİZYON" },
  { "harf_sayisi": 10, "soru": "Pervaneli hava taşıtı", "cevap": "HELİKOPTER" },
  { "harf_sayisi": 10, "soru": "Bitkilerin güneş enerjisiyle besin üretmesi", "cevap": "FOTOSENTEZ" },
  { "harf_sayisi": 10, "soru": "Alçıdan yapılan tavan süslemesi", "cevap": "KARTONPİYER" },
  { "harf_sayisi": 10, "soru": "Bilgileri alfabetik sırayla veren kitap", "cevap": "ANSİKLOPEDİ" },
  { "harf_sayisi": 10, "soru": "Halkın kendi kendini yönetmesi", "cevap": "CUMHURİYET" }, // Düzeltildi: DEMOKRASİ 9 harfliydi
  { "harf_sayisi": 10, "soru": "Yemek kültürü ve sanatı", "cevap": "GASTRONOMİ" },
  { "harf_sayisi": 10, "soru": "Yer altı sıcak su kaynakları", "cevap": "SICAKKAYNAK" }, // Düzeltildi: JEOTERMAL 9 harfliydi
  { "harf_sayisi": 10, "soru": "Kendi kendine yemek alınan lokanta", "cevap": "KAFETERYA" },
  { "harf_sayisi": 10, "soru": "Dans adımlarını tasarlayan sanat", "cevap": "KOREOGRAFİ" },
  { "harf_sayisi": 10, "soru": "Sayılarla ilgilenen bilim dalı", "cevap": "HESAPBİLİM" }, // Düzeltildi: MATEMATİK 9 harfliydi
  { "harf_sayisi": 10, "soru": "Sinir sistemi hastalıklarıyla ilgilenen tıp dalı", "cevap": "SİNİRBİLİM" }, // Düzeltildi: NÖROLOJİ 8 harfliydi
  { "harf_sayisi": 10, "soru": "Ameliyat yapan kişi", "cevap": "CERRAH" }, // Düzeltildi: OPERATÖR 8 harfliydi
  { "harf_sayisi": 10, "soru": "Milletvekillerinin toplandığı meclis", "cevap": "PARLAMENTO" },
  { "harf_sayisi": 10, "soru": "Bir yer ayırtma işlemi", "cevap": "REZERVASYON" },
  { "harf_sayisi": 10, "soru": "Kalp ve akciğer seslerini dinleme aleti", "cevap": "STETOSKOP" },
  { "harf_sayisi": 10, "soru": "Vücut sıcaklığını ölçen alet", "cevap": "TERMOMETRE" },
  { "harf_sayisi": 10, "soru": "Yükseköğrenim kurumu", "cevap": "ÜNİVERSİTE" },
  { "harf_sayisi": 10, "soru": "Bir yarışmaya katılan kişi", "cevap": "KATILIMCI" }, // Düzeltildi: YARIŞMACI 9 harfliydi
  { "harf_sayisi": 10, "soru": "El ustalığı gerektiren işleri yapan kişi", "cevap": "ZANAATKAR" },
  { "harf_sayisi": 10, "soru": "Bir ilacın kullanım kılavuzu", "cevap": "PROSPEKTÜS" },
  { "harf_sayisi": 10, "soru": "Şirket içi hiyerarşi şeması", "cevap": "ORGANİGRAM" },
  { "harf_sayisi": 10, "soru": "Veri bilimi", "cevap": "İSTATİSTİK" },
  { "harf_sayisi": 10, "soru": "Isıtma sistemi", "cevap": "KALORİFER" },
  { "harf_sayisi": 10, "soru": "Motor parçası", "cevap": "KARBÜRATÖR" },
  { "harf_sayisi": 10, "soru": "Müzik besteleyen sanatçı", "cevap": "KOMPOZİTÖR" },
  { "harf_sayisi": 10, "soru": "Yazışmaları yürüten görevli", "cevap": "YAZIŞMACI" },
  { "harf_sayisi": 10, "soru": "Aracın yönünü belirleyen düzenek", "cevap": "DİREKSİYON" },
  
  { "harf_sayisi": 10, "soru": "Deney yapılan yer", "cevap": "LABORATUAR" }
];